$ErrorActionPreference = 'Stop'

$root = Split-Path $PSScriptRoot -Parent
$fontFolder = Join-Path $root 'fonts'
$outputFile = Join-Path $root 'fonts.js'

if (-not (Test-Path $fontFolder)) {
    New-Item -ItemType Directory -Path $fontFolder -Force | Out-Null
}

$allowed = @('.ttf', '.otf', '.woff', '.woff2')

$files = Get-ChildItem -Path $fontFolder -File -Recurse |
    Where-Object { $allowed -contains $_.Extension.ToLowerInvariant() } |
    Sort-Object FullName

$items = foreach ($file in $files) {
    $relative = $file.FullName.Substring($fontFolder.Length).TrimStart('\', '/') -replace '\\', '/'

    [PSCustomObject]@{
        file = $relative
        name = $file.BaseName
    }
}

$json = if ($items.Count -eq 0) {
    '[]'
} else {
    $items | ConvertTo-Json -Depth 3
}

$content = @"
// Auto-generated by tools/generate-font-list.ps1
// Do not edit manually unless you know what you are doing.
window.FONT_FILES = $json;
"@

Set-Content -Path $outputFile -Value $content -Encoding UTF8

Write-Host ''
Write-Host 'Font manifest generated successfully.' -ForegroundColor Green
Write-Host "Fonts found: $($items.Count)"
Write-Host "Output: $outputFile"
